config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'

  devise_for :users

  root to: 'pages#home'

  get "/onboarding", to: "pages#home", as: "onboarding"

  get "/tutorial", to: "pages#tutorial", as: "tutorial"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :media, only: [:index, :show]
  delete "/influencers/:id", to: "influencers#show"
  resources :influencers, only: [:show] do
    get "/media_type/:formata", to: "influencers#collect_media", as: "type"
    resources :preferences, only: [:create, :destroy]
  end

  resources :states, only: [:create, :update]
  resources :preferences, only: [:index, :create]

end

app/models/influencer.rb
class Influencer < ApplicationRecord
  has_many :accounts
  has_many :media
  has_many :platforms, through: :accounts
  has_many :preferences, dependent: :destroy
end

app/controllers/influencers_controller.rb
class InfluencersController < ApplicationController

  def show

    # Initialize instance variables
    @influencer = Influencer.find(params[:id])
    @all_influencers = Influencer.all

    # Initialize Influencer list for user
    @my_preference = Preference.where(user: current_user)
    @my_influencers = @my_preference.map { |p| p.influencer }
    @not_my_influencers = @all_influencers.reject { |i| @my_influencers.include?(i) }

    # Initialize user States
    @all_my_states = State.where(user: current_user)
    @my_states = @all_my_states.select { |s| @my_influencers.include?(s.medium.influencer) }

    @my_states.map! { |state| increment_state!(state.medium) }
    sort_by_algo(@my_states)

    @preference = Preference.find_by(user: current_user, influencer: @influencer)

    form = Format.find_by(type_of: "article")
    @media = @influencer.media.where(format: form)

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def collect_media
    @influencer = Influencer.find(params[:influencer_id])
    @format = Format.find_by(type_of: params[:formata])
    @media = @influencer.media.where(format: @format)

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  # searches for a state record for each medium associated to the current user
  def find_state(medium)
    State.find_by(medium: medium, user: current_user)
  end

  # sorts the list with algorithm - in state model
  def sort_by_algo(state_list)
    state_list.sort_by(&:algie_check)
  end

  # increases the display count of the state record by 1
  def increment_state!(medium)
    find_state(medium).increment!(:display_count)
  end
end

app/views/influencers/_influencer_modal.html.erb
<!-- Default displays the details of the first influencer in the list -->


<!-- This is what is rendered into the right container of the influencer's modal -->

<div class="close-header title-top-bar top-bar-nav-modal bottom-border">
  <p data-dismiss="modal" aria-hidden="true">
    <i class="fas fa-times gray"></i>
  </p>
</div>

<div class="sidebar">
  <h2 class="dark">My Influencers</h2><br>

  <!-- Lists the influencer's included in the user's preferences -->

  <% @my_influencers.each do | influencer | %>
    <h3><%=link_to influencer.name, influencer_path(influencer), :class => "blue", remote: true %></h3>
  <% end %>

  <br><br>

  <!-- Lists all the influencer's available -->
  <h2 class="dark">Top Influencers</h2><br>

  <!-- map preferences to obtain influencer ids -->
  <%# pref_filter = @my_preference.map do | pref | %>
    <%# pref.influencer.id %>
  <%# end %>

  <!-- display only influencers NOT in the user's list -->
  <% @not_my_influencers.sort.each do | influencer | %>

    <%# unless pref_filter.include?(influencer.id) %>
      <h3><%=link_to influencer.name, influencer_path(influencer), :class => "gray", remote: true %></h3>
      <%# end %>
  <% end %>
</div>

<!-- Displays the influencer avatar and name -->
<div class="name-bar">
    <h1 class="dark"><%= @influencer.name %></h1>

    <% if @preference.nil? %>

      <%= link_to influencer_preferences_path(@influencer), method: :post, remote: true do %>
      <p class="button-outline">Follow</p>
      <% end %>

    <% else %>
      <%= link_to influencer_preference_path(@influencer, @preference), method: :delete, remote: true do %>
      <p class="button-outline">Unfollow</p>
      <% end %>
    <% end %>
</div>

<div class="avatar-container">
  <img src="<%= image_path(@influencer.photo) %>" class="influencer-avatar">
  <%#= image_tag(image_path(@influencer.photo), :alt => @influencer.name, :class => "influencer-avatar") %>
</div>

<!-- Influencer biography displayed here -->

<div class="bio-container">
  <p><%= @influencer.bio %></p>
</div>

<div class="inner-left">

  <!-- Filter tags to toggle between colelcted articles -->

  <h3>Filter By</h3>
  <br>
    <h4>
    <%=link_to influencer_type_path(influencer_id: @influencer.id,
      formata: "article"), :class => "blue", remote: true do %>
      <i class="far fa-file-alt"></i> Articles
      <% end %>
  </h4>

  <h4>

    <%=link_to influencer_type_path(influencer_id: @influencer.id,
      formata: "podcast"), :class => "blue", remote: true do %>
      <i class="fas fa-headphones"></i> Podcasts
      <% end %>
  </h4>

  <h4>
    <%=link_to influencer_type_path(influencer_id: @influencer.id,
      formata: "video"), :class => "blue", remote: true do %>
      <i class="fas fa-tv"></i> Videos
    <% end %>
  </h4>

  <h4>

    <%=link_to influencer_type_path(influencer_id: @influencer.id,
      formata: "tweet"), :class => "blue", remote: true do %>
        <i class="fab fa-twitter"></i> Tweets
      <% end %>
  </h4>

  <br>

  <!-- Renders external links to the influencer's accounts -->

  <h3>Accounts</h3>
  <br>

  <div class="accounts-container">
    <% @influencer.accounts.each do |account| %>
      <h4><%=link_to account.platform.name, account.url, :class => "blue", target: "_blank" %></h4>
    <% end %>
  </div>

</div>

<!-- Renders content from the _medium partial -->

<div class="inner-right">

<%= render partial: "influencers/medium" %>

</div>

app/views/influencers/_medium.html.erb
<div>
  <h3>My Collection - <em><%= @format.nil? ? "Article" : @format.type_of.capitalize%></em></h3>
</div>

<br>

  <% if @media.any? %>
    <div>
      <% @media.each do | medium | %>
      <h4><%= link_to medium.title, medium.url, :class => "blue", target: "_blank" %></h4>
      <% end %>
    </div>

    <% else %>
      <div class="empty-display">
      <h4 class="gray" style=" height: 100px;">
      <em style="text-align: center;">Nothing to display</em></h4>
      </div>
  <% end %>

app/views/influencers/collect_media.js.erb
function listMedia(innerHTML) {
  const videoContainer = document.querySelector('.inner-right');
  videoContainer.innerHTML = innerHTML;
}

listMedia('<%= j render "medium" %>');

app/views/influencers/show.html.erb
<h1 class="dark">THIS IS THE INFLUENCER SHOW</h1>

app/views/influencers/show.js.erb
function refreshInfluencer(innerHTML) {
  const influencerContainer = document.querySelector('.modal-container');
  influencerContainer.innerHTML = innerHTML;
}

function refreshBubble(innerHTML) {
  const bubbleContainer = document.getElementById('bubble_update');
  bubbleContainer.innerHTML = innerHTML;
}

function refreshWindow(innerHTML) {
  const windowContainer = document.getElementById('window_update');
  windowContainer.innerHTML = innerHTML;
}

refreshInfluencer('<%= j render "influencer_modal", influencer: @influencer %>');

refreshBubble('<%= j render "shared/index-bubble" %>');
refreshWindow('<%= j render "shared/index-bubble-window" %>');

document.querySelectorAll(".bubble-wrapper").forEach( bubble => {

  bubble.addEventListener("click", (e) => {
    console.log("test")
    const bubblesWindow = document.querySelectorAll(".bubble-right")
    bubblesWindow.forEach( bbl => {
      if ( bbl.classList.contains("hidden-page") ){
        bbl.classList.toggle("hidden-page");
      }
    });

    const hh = e.currentTarget.attributes["data-target-id"].value ;
    document.getElementById(hh).classList.toggle("hidden-page");
  })
});

// Event listener to toggle the article hide on CLOSE button.

document.querySelectorAll(".close-button").forEach( button => {

  button.addEventListener("click", (e) => {

    const close = e.currentTarget.parentNode.parentNode.parentNode
    close.classList.toggle("hidden-page");

  })
});