config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'

  devise_for :users

  root to: 'pages#home'

  get "/onboarding", to: "pages#home", as: "onboarding"

  get "/tutorial", to: "pages#tutorial", as: "tutorial"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :media, only: [:index, :show]
  delete "/influencers/:id", to: "influencers#show"
  resources :influencers, only: [:show] do
    get "/media_type/:formata", to: "influencers#collect_media", as: "type"
    resources :preferences, only: [:create, :destroy]
  end

  resources :states, only: [:create, :update]
  resources :preferences, only: [:index, :create]

end

app/views/shared/_background-side.html.erb
<script>
  document.querySelectorAll(".close-button").forEach((closeButton) => {
    closeButton.addEventListener("click", () => {
      document.querySelector("#background-bubble").classList.toggle("hidden-page");
    });
  });
</script>
<!--
<div class="bubble-right scroll hidden-page" id="background-bubble" style="
  background: transparent;
  border: 3px solid rgba(255, 255, 255, 0.2);
">
  <div class="fixed-top top-bar-nav bottom-border" style="
    display: none;
    /*border-bottom: 1px solid rgba(255, 255, 255, 0.6);*/
  ">
    <div class="menu-window">
    </div>
  </div>

  <div class="content article-text-style" style="
    position: initial;
    padding-right: initial;
  ">
    <div style="
      display: flex;
      justify-content: center;
      align-items: center;
      width: 100%;
      height: calc(100vh - 235px);
    ">
      <h1 style="
      font-size: 5vw;
      font-family: poynter-oldstyle-display, serif;
      font-weight: 400;
      font-style: normal;
        display: inline-block;
        color: rgba(255, 255, 255, 0.2);
        text-align: center;

      ">influencr.io</h1>
    </div>
  </div>
</div>
 -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_index-bubble-window.html.erb
<%#= render "shared/background-side" %>
<% @my_states.each do |state| %>
  <div class="bubble-right scroll" id="medium<%= state.medium.id %>">
    <div class="fixed-top top-bar-nav bottom-border">

      <!-- top menu -->
      <div class="menu-window">

        <!-- FULLSCREEN / Redirect to medium show page -->
        <%=link_to medium_path(state.medium.id) do %>
          <p class="click-aspect menu-item-window">
          <i class="fas fa-external-link-alt gray"></i>&nbsp&nbsp
          </p>
        <% end %>

         <!-- READ / Update read state -->
        <%=link_to state_path(state.id),method: :patch, remote: true do %>
          <p id="<%= state.id %>readstate" class="click-aspect menu-item-window gray">
            <i class="fas fa-check"></i>&nbsp&nbsp
          </p>
        <% end %>

        <!-- <p class="menu-item-window">|</p> -->

        <!-- CLOSE -->
        <p class="close-button click-aspect menu-item-window">
          <i class="fas fa-times gray"></i>
        </p>
      </div>
    </div>

    <div class="content article-text-style">
      <h3 class="title_styling"><%= state.medium.title %></h3>
      <br>
      <h3 class="influencer_name_styling">By <%= state.medium.influencer.name %></h3>
      <em><%= link_to "Original Source", state.medium.url, :class => "blue-small", target: "_blank" %></em>
      <br><br>
      <p class="body_styling"><%= simple_format(state.medium.content) %></p>
    </div>
  </div>
<% end %>

app/views/shared/_index-bubble.html.erb
<!-- Container Left Side -->
<% @my_states.each do |state| %>

  <!-- Going through all Medium from State to diplay in a wrapper -->
  <div class="bubble-wrapper" data-target-id="medium<%= state.medium.id %>">

    <!-- Storing the format in a CSS class style -->
    <div class='bubble <%=state.medium.format.type_of%>'>

      <!-- Displaying Influencer Name for all media format in a CSS Title class -->
      <!-- Inner-round Div = Curve inner corner top right of bubbles -->
      <div class="title-top-bar"> <div id="inner-round"></div> <h2 class="bubble-influencer"> <%= state.medium.influencer.name %> </h2> </div>

      <!-- Display different content for Format type -->

      <!-- ARTICLE-->
      <% if state.medium.format.type_of == "article" %>
        <div class="icon-container"><i class="far fa-file-alt"></i></div>

        <div class="bubble-title">
          <h4> <%= state.medium.title %> </h4>
        </div>

        <div class="content">
          <p> <%= simple_format(state.medium.content.first(100)) if state.medium.content %> </p>
        </div>

      <!-- TWEET-->
      <% elsif state.medium.format.type_of == "tweet" %>
        <div class="icon-container"><i class="fab fa-twitter"></i></div>
        <div class="bubble-title">
          <h4> 1 new tweet </h4>
        </div>
        <div class="content">
          <h2>Tweet</h2>
          <p> <%= state.medium.content if state.medium.content %> </p>
        </div>

      <!-- PODCAST-->
      <% elsif state.medium.format.type_of == "podcast" %>
        <div class="icon-container"><i class="fas fa-headphones"></i></div>
        <div class="bubble-title">
          <h4><%= state.medium.title %></h4>
        </div>
        <div class="content">

        <!-- replace with erb-embedcode for each media -->

          <iframe width="100%" height="80px" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/319411042&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe>

         </div>

      <!-- VIDEO-->
      <% elsif state.medium.format.type_of == "video" %>
        <div class="icon-container"><i class="fas fa-tv"></i></div>
        <div class="bubble-title">
          <h4><%= state.medium.title %></h4>
        </div>
        <div class="content">

        <!-- replace with erb-embedcode for each media -->

          <iframe width="100%" height="100%" src="https://www.youtube.com/embed/m8DQpqJwo3Q" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_logo.html.erb
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 100 81.9" xml:space="preserve">
  <g>
    <path class="st0 <%= myclass %>" d="M72.8,56.2c1.2-0.4,2.9-0.4,4.1-0.4c0.7,0,1.5,0,2.2,0c0.7,0,1.5,0,2.2,0c5.1,0,9.8-2.1,13.4-6.1
      c3.4-3.6,5.3-8.5,5.3-13.4c0-5.1-2-9.7-5.6-13c-3.4-3.1-8.1-4.8-13.1-4.8c-1.8,0-3.4,0.3-4.7,0.6c0-1.2,0-2.5,0-3.8
      c0-3.5-2.2-8.4-12.9-11.9C56.9,1.2,47.8,0,38.3,0c-9.5,0-18.6,1.2-25.4,3.5C2.2,7,0,11.9,0,15.4c0,14.9,0.5,26.8,3,36.2
      C5.5,60.8,9.8,67.8,17.4,75c4.8,4.5,12,6.9,20.9,6.9c8.9,0,16.1-2.4,20.9-6.9c5.8-5.5,9.7-11.1,12.7-18.2
      C71.9,56.7,72,56.5,72.8,56.2z M68,55.2c-2.6,6.3-6.1,11.5-11.7,16.8c-3.9,3.7-10,5.8-18,5.8c-8,0-14.1-2.1-18-5.8
      C6.5,58.9,4.2,46.8,4.2,15.4c0-6.2,15.3-11.3,34.1-11.3s34.1,5,34.1,11.3c0,3.2,0,6.1-0.1,8.9c0.2,0,0.4,0,0.6,0
      c2.1,0,4.4-1.6,8.3-1.6c4,0,7.7,1.3,10.3,3.7c2.7,2.5,4.2,6,4.2,9.9c0,3.8-1.5,7.7-4.2,10.6c-2.8,3-6.5,4.7-10.4,4.7
      c-1.4,0-2.9-0.1-4.4-0.1C73.1,51.6,69.3,52.1,68,55.2z"/>
    <path class="st0 <%= myclass %>"" d="M81.3,46c4.8-0.5,8.9-4.5,8.9-9.6c0-4.8-3.5-7.9-8.9-7.9c-4.5,0-7.7,2.3-9.3,5.2c-0.2,2.6-1.3,10.6-1.6,12.9
      c1.2-0.7,2.8-0.9,4.5-0.9c1.9,0,4,0.2,5.5,0.2C80.7,46,81,46,81.3,46z M76,35.1c0.8-1,2.3-2.4,5.2-2.4c2.1,0,4.7,0.6,4.7,3.7
      c0,3.1-2.6,5.2-5.1,5.4c-0.1,0-0.2,0-0.5,0c-0.6,0-1.3,0-2.1-0.1c-0.9-0.1-1.9-0.1-3-0.1C75.6,39.3,75.9,36.8,76,35.1z"/>
    <path class="st0 <%= myclass %>" d="M62.8,12.2c-0.5-0.3-1.1-0.1-1.4,0.4c-0.3,0.5-0.1,1.1,0.4,1.4c1.4,0.7,2.2,1.6,2.2,2.2c0,0.6-0.6,1.4-2.2,2.2
      c-3.9-2.8-12.9-4.8-23.4-4.8c-10.5,0-19.6,2-23.4,4.8c-1.6-0.8-2.2-1.7-2.2-2.2c0-0.7,0.8-1.5,2.2-2.2c0.5-0.3,0.7-0.9,0.4-1.4
      c-0.3-0.5-0.9-0.7-1.4-0.4c-2.2,1.2-3.3,2.5-3.3,4c0,3.3,5.3,5.6,12.6,6.9c-0.9,1.1-1.4,2.8-1.4,5.2v10.3c-0.2,0.1-0.4,0.3-0.6,0.4
      l-4.6,4.6c-0.9,0.9-1.7,2.7-1.7,4v7.6c0,1.3,1.1,2.4,2.4,2.4h11.2c1.3,0,2.4-1.1,2.4-2.4v-7.6c0-1.3-0.8-3.1-1.7-4l-4.6-4.6
      c-0.2-0.2-0.4-0.3-0.6-0.4V28.3c0-2,0.4-3.3,1.1-4c0.5-0.5,1.2-0.7,2.2-0.6c0.1,0,0.1,0,0.2,0c3.5,0.4,7.3,0.6,11.1,0.6
      c13.8,0,27.8-2.8,27.8-8.1C66,14.7,64.9,13.3,62.8,12.2z"/>
  </g>
</svg>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>